name: Documentation
on:
  - push
  - pull_request
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: ThreeBodyTB
            using ThreeBodyTB
            doctest(ThreeBodyTB)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#name: Documentation
#
#on:
#  push:
#jobs:
#  makedoc:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        julia-version: [1.5]
#        julia-arch: [x86]
#        os: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: julia-actions/setup-julia@latest
#        with:
#          version: ${{ matrix.julia-version }}
#      - name: Install dependencies
#        run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#      - name: Build and deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: julia --project=docs/ --color=yes docs/make.jl